/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 */

@interface _LSInstallationManager : NSObject {
    NSXPCConnection * _connection;
}

@property (readonly) NSXPCConnection *connection;

+ (id)manager;

- (id)connection;
- (void)dealloc;
- (id)init;
- (bool)install:(id)arg1 withError:(id*)arg2;
- (bool)removeSystemApplicationWithBundleIdentifier:(id)arg1;
- (bool)restoreSystemApplicationWithBundleIdentifier:(id)arg1;
- (bool)uninstall:(id)arg1 withError:(id*)arg2;

@end
