/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 */

@interface _LSSpringBoardCall : NSObject <NSCopying> {
    NSString * _applicationIdentifier;
    bool  _callCompletionHandlerWhenFullyComplete;
    NSXPCConnection * _clientXPCConnection;
    NSDictionary * _launchOptions;
    bool  _promptForSchemeApprovalIfNeeded;
    NSString * _schemeIfNotFileURL;
}

@property (copy) NSString *applicationIdentifier;
@property bool callCompletionHandlerWhenFullyComplete;
@property (retain) NSXPCConnection *clientXPCConnection;
@property (copy) NSDictionary *launchOptions;
@property bool promptForSchemeApprovalIfNeeded;

+ (id)springBoardQueue;

- (id)applicationIdentifier;
- (bool)callCompletionHandlerWhenFullyComplete;
- (void)callSpringBoardWithCompletionHandler:(id /* block */)arg1;
- (void)callWithCompletionHandler:(id /* block */)arg1;
- (id)clientXPCConnection;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)debugDescription;
- (id)launchOptions;
- (void)lieWithCompletionHandler:(id /* block */)arg1;
- (void)promptAndCallSpringBoardWithCompletionHandler:(id /* block */)arg1;
- (bool)promptForSchemeApprovalIfNeeded;
- (void)setApplicationIdentifier:(id)arg1;
- (void)setCallCompletionHandlerWhenFullyComplete:(bool)arg1;
- (void)setClientXPCConnection:(id)arg1;
- (void)setLaunchOptions:(id)arg1;
- (void)setPromptForSchemeApprovalIfNeeded:(bool)arg1;

@end
