/* Generated by RuntimeBrowser.
 */

@protocol _UIScrollViewIndexEntryTrimmerDelegate <NSObject>

@required

- (bool)_scrollViewIndexEntryTrimmer:(_UIScrollViewIndexEntryTrimmer *)arg1 entryIsPlaceholder:(id)arg2;
- (id)_scrollViewIndexEntryTrimmer:(_UIScrollViewIndexEntryTrimmer *)arg1 placeholderEntryBetweenEntryBefore:(id)arg2 entryAfter:(id)arg3;
- (bool)_scrollViewIndexEntryTrimmer:(_UIScrollViewIndexEntryTrimmer *)arg1 startingOrEndingEntryMustBePreserved:(id)arg2;

@end
