/* Generated by RuntimeBrowser.
 */

@protocol MRTelevisionMessageQueueDelegate <NSObject>

@required

- (unsigned long long)messageQueue:(MRTelevisionMessageQueue *)arg1 processData:(NSData *)arg2 atReadPosition:(long long)arg3;

@end
