/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PowerLog.framework/PowerLog
 */

@interface PLModelingUtilities : NSObject

+ (bool)alsCurveHigherThanDefault;
+ (double)defaultBatteryEnergyCapacity;
+ (double)duetDiscretionaryBudget;
+ (bool)internalBuild;
+ (bool)isHeySiriAlwaysOn;
+ (bool)isIPod;
+ (bool)isLowPowerModeSupported;
+ (bool)isNarrowScreen;
+ (bool)isiPad;
+ (bool)isiPhone;
+ (id)valueForMobileGestaltCapability:(id)arg1;

@end
