/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMAggregateMessagePartChatItem : IMTextMessagePartChatItem {
    NSArray * _subparts;
}

@property (nonatomic, readonly, copy) NSArray *subparts;

- (void).cxx_destruct;
- (id)_initWithItem:(id)arg1 messagePartRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2 subparts:(id)arg3;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)subparts;

@end
