/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMAssociatedStickerChatItem : IMAssociatedMessageChatItem {
    NSString * _transferGUID;
}

@property (nonatomic, readonly, copy) NSString *transferGUID;

- (void).cxx_destruct;
- (id)_initWithItem:(id)arg1 sender:(id)arg2 transferGUID:(id)arg3;
- (bool)canDelete;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)transferGUID;

@end
