/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMAudioMessageChatItem : IMExpirableMessageChatItem

- (bool)isAttachmentContiguousWithChatItem:(id)arg1;

@end
