/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMBalloonPlugin : NSObject {
    NSMutableArray * _balloonControllerPool;
    Class  _browserClass;
    NSString * _browserDisplayName;
    long long  _browserGroup;
    NSString * _browserImageName;
    NSString * _browserImagePath;
    Class  _bubbleClass;
    NSBundle * _bundle;
    Class  _customTypingIndicatorLayerClass;
    Class  _datasourceClass;
    Class  _entryClass;
    NSString * _identifier;
    NSMutableDictionary * _messageToBalloonControllerMap;
    NSMutableDictionary * _messageToDatasourceMap;
    bool  _pluginLoaded;
    bool  _showInBrowser;
}

@property (nonatomic, retain) NSMutableArray *balloonControllerPool;
@property (getter=isBetaPlugin, nonatomic, readonly) bool betaPlugin;
@property (nonatomic, retain) Class browserClass;
@property (nonatomic, retain) NSString *browserDisplayName;
@property (nonatomic) long long browserGroup;
@property (nonatomic, retain) NSString *browserImageName;
@property (nonatomic, retain) NSString *browserImagePath;
@property (nonatomic, retain) Class bubbleClass;
@property (nonatomic, retain) NSBundle *bundle;
@property (nonatomic, retain) Class customTypingIndicatorLayerClass;
@property (nonatomic, retain) Class datasourceClass;
@property (nonatomic, retain) Class entryClass;
@property (nonatomic, retain) NSString *identifier;
@property (nonatomic, retain) NSMutableDictionary *messageToBalloonControllerMap;
@property (nonatomic, retain) NSMutableDictionary *messageToDatasourceMap;
@property (nonatomic) bool pluginLoaded;
@property (nonatomic) bool showInBrowser;
@property (nonatomic, readonly) NSString *version;

- (void).cxx_destruct;
- (id)_getControllerFromReusePoolForChatItem:(id)arg1;
- (void)_loadBundle;
- (id)balloonControllerForChatItem:(id)arg1;
- (id)balloonControllerPool;
- (Class)browserClass;
- (id)browserDisplayName;
- (long long)browserGroup;
- (id)browserImageName;
- (id)browserImagePath;
- (Class)bubbleClass;
- (id)bundle;
- (Class)customTypingIndicatorLayerClass;
- (id)dataSourceForPluginPayload:(id)arg1;
- (Class)datasourceClass;
- (void)dealloc;
- (Class)entryClass;
- (id)existingBalloonControllerWithMessageGUID:(id)arg1;
- (id)existingDataSourceForMessageGUID:(id)arg1;
- (id)identifier;
- (id)initWithBundle:(id)arg1;
- (void)insertDataSource:(id)arg1 forGUID:(id)arg2;
- (bool)isBetaPlugin;
- (id)messageToBalloonControllerMap;
- (id)messageToDatasourceMap;
- (void)moveController:(id)arg1 toReusePoolFromChatItem:(id)arg2;
- (bool)pluginLoaded;
- (void)removeController:(id)arg1 forChatItem:(id)arg2;
- (void)setBalloonControllerPool:(id)arg1;
- (void)setBrowserClass:(Class)arg1;
- (void)setBrowserDisplayName:(id)arg1;
- (void)setBrowserGroup:(long long)arg1;
- (void)setBrowserImageName:(id)arg1;
- (void)setBrowserImagePath:(id)arg1;
- (void)setBubbleClass:(Class)arg1;
- (void)setBundle:(id)arg1;
- (void)setCustomTypingIndicatorLayerClass:(Class)arg1;
- (void)setDatasourceClass:(Class)arg1;
- (void)setEntryClass:(Class)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setMessageToBalloonControllerMap:(id)arg1;
- (void)setMessageToDatasourceMap:(id)arg1;
- (void)setPluginLoaded:(bool)arg1;
- (void)setShowInBrowser:(bool)arg1;
- (bool)showInBrowser;
- (bool)supportsControllerReuse;
- (void)unloadBundle;
- (id)version;

@end
