/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMDateChatItem : IMTranscriptChatItem

@property (nonatomic, readonly) NSDate *date;

- (id)_initWithItem:(id)arg1;
- (id)date;

@end
