/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMEmoteMessageChatItem : IMMessageChatItem

@property (nonatomic, readonly, copy) NSAttributedString *text;

- (id)_initWithItem:(id)arg1;
- (id)text;

@end
