/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMExpirableMessageChatItem : IMAttachmentMessagePartChatItem

@property (nonatomic, readonly) bool isPlayed;
@property (nonatomic, readonly) bool isSaved;

- (bool)isPlayed;
- (bool)isSaved;

@end
