/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMExpressiveSendAsTextChatItem : IMTranscriptChatItem {
    NSString * _text;
}

@property (nonatomic, readonly, copy) NSString *text;

- (void).cxx_destruct;
- (id)_initWithItem:(id)arg1 text:(id)arg2;
- (id)text;

@end
