/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMMessageAcknowledgmentChatItem : IMAssociatedMessageChatItem {
    long long  _messageAcknowledgmentType;
}

@property (nonatomic, readonly) long long messageAcknowledgmentType;

- (id)_initWithItem:(id)arg1 sender:(id)arg2 messageAcknowledgmentType:(long long)arg3;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (long long)messageAcknowledgmentType;

@end
