/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMReportSpamChatItem : IMTranscriptChatItem {
    bool  _wasReportedAsSpam;
}

@property (nonatomic, readonly) bool wasReportedAsSpam;

- (id)_initWithItem:(id)arg1 wasReportedAsSpam:(bool)arg2;
- (bool)wasReportedAsSpam;

@end
