/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMSenderChatItem : IMTranscriptChatItem {
    IMHandle * _handle;
}

@property (nonatomic, readonly) IMHandle *handle;

- (void).cxx_destruct;
- (id)_initWithItem:(id)arg1 handle:(id)arg2;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)handle;

@end
