/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMTextMessagePartChatItem : IMMessagePartChatItem {
    NSAttributedString * _subject;
}

@property (nonatomic, readonly, copy) NSAttributedString *subject;

- (void).cxx_destruct;
- (id)_initWithItem:(id)arg1 text:(id)arg2 index:(long long)arg3 messagePartRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg4 subject:(id)arg5;
- (id)_initWithItem:(id)arg1 text:(id)arg2 index:(long long)arg3 messagePartRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg4 subject:(id)arg5 shouldDisplayLink:(bool)arg6;
- (id)_initWithItem:(id)arg1 text:(id)arg2 index:(long long)arg3 messagePartRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg4 subject:(id)arg5 visibleAssociatedMessageChatItems:(id)arg6;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)setShouldDisplayRichLink:(bool)arg1;
- (bool)shouldDisplayRichLink;
- (id)subject;

@end
