/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface _INPBCallMetricsValue : PBCodable <NSCopying> {
    struct { 
        unsigned int timeToEstablish : 1; 
    }  _has;
    double  _timeToEstablish;
    PBUnknownFields * _unknownFields;
}

@property (nonatomic) bool hasTimeToEstablish;
@property (nonatomic) double timeToEstablish;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;

+ (id)options;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasTimeToEstablish;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setHasTimeToEstablish:(bool)arg1;
- (void)setTimeToEstablish:(double)arg1;
- (double)timeToEstablish;
- (id)unknownFields;
- (void)writeTo:(id)arg1;

@end
