/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INPaymentAccount : NSObject <NSCopying, NSSecureCoding> {
    NSString * _accountNumber;
    long long  _accountType;
    INSpeakableString * _nickname;
    INSpeakableString * _organizationName;
}

@property (nonatomic, readonly, copy) NSString *accountNumber;
@property (nonatomic, readonly) long long accountType;
@property (nonatomic, readonly, copy) INSpeakableString *nickname;
@property (nonatomic, readonly, copy) INSpeakableString *organizationName;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_dictionaryRepresentation;
- (id)accountNumber;
- (long long)accountType;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithNickname:(id)arg1 number:(id)arg2 accountType:(long long)arg3 organizationName:(id)arg4;
- (bool)isEqual:(id)arg1;
- (id)nickname;
- (id)organizationName;

@end
