/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLArrayTypeInternal : MTLArrayType {
    unsigned int  _arrayLength;
    id  _details;
    unsigned long long  _elementType;
    unsigned int  _stride;
}

- (unsigned long long)arrayLength;
- (void)dealloc;
- (id)elementArrayType;
- (id)elementStructType;
- (unsigned long long)elementType;
- (id)formattedDescription:(unsigned long long)arg1;
- (id)initWithArrayLength:(unsigned long long)arg1 elementType:(unsigned long long)arg2 stride:(unsigned long long)arg3 details:(id)arg4;
- (unsigned long long)stride;

@end
