/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLStructTypeInternal : MTLStructType {
    NSDictionary * _dictionary;
    NSArray * _members;
}

- (void)dealloc;
- (id)description;
- (id)formattedDescription:(unsigned long long)arg1;
- (id)initWithMembers:(id*)arg1 count:(unsigned long long)arg2;
- (id)memberByName:(id)arg1;
- (id)members;

@end
