/* Generated by RuntimeBrowser
   Image: /usr/lib/libnfshared.dylib
 */

@interface NFAWDSERestrictedModeEntered : NSObject <NFAWDEventProtocol> {
    AWDNFCSERestrictedModeEnteredEvent * _metric;
}

@property (nonatomic, retain) NSData *attackLog;
@property (nonatomic) bool contactlessMode;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) AWDNFCSERestrictedModeEnteredEvent *metric;
@property (nonatomic, retain) NSString *platformIdentifier;
@property (nonatomic, retain) NSData *restrictedModeID;
@property (readonly) Class superclass;

- (id)attackLog;
- (bool)contactlessMode;
- (void)dealloc;
- (id)getMetric;
- (unsigned int)getMetricId;
- (id)init;
- (id)metric;
- (id)platformIdentifier;
- (id)restrictedModeID;
- (void)setAttackLog:(id)arg1;
- (void)setContactlessMode:(bool)arg1;
- (void)setMetric:(id)arg1;
- (void)setPlatformIdentifier:(id)arg1;
- (void)setRestrictedModeID:(id)arg1;

@end
