/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

@interface BWAggdDataReporter : NSObject {
    NSObject<OS_dispatch_queue> * _aggdDispatchQueue;
}

+ (void)initialize;
+ (id)sharedInstance;

- (id)_aggdGNRProcessingStatusStringFromProcessingStatus:(int)arg1;
- (id)_aggdSDOFProcessingStatusStringFromProcessingStatus:(int)arg1;
- (id)_aggdShutterLagStringForCaptureType:(int)arg1 wideSubCaptureType:(int)arg2 teleSubCaptureType:(int)arg3 stillDuringVideo:(bool)arg4 frontCamera:(bool)arg5;
- (id)_aggdStereoFusionProcessingStatusStringFromProcessingStatus:(int)arg1;
- (id)_aggdStereoFusionProcessingTypeStringForCaptureType:(int)arg1 isStereoFusionCapture:(bool)arg2 wideSubCaptureType:(int)arg3 teleSubCaptureType:(int)arg4 isOriginalImage:(bool)arg5;
- (void)_incrementValueOfAggdScalarKey:(id)arg1;
- (void)_pushValue:(double)arg1 aggdDistributionKey:(id)arg2;
- (void)dealloc;
- (id)init;
- (void)reportGNRSampleBufferProcessorProcessingStatus:(int)arg1;
- (void)reportSDOFSampleBufferProcessorProcessingStatus:(int)arg1;
- (void)reportShutterLag:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1 captureType:(int)arg2 wideSubCaptureType:(int)arg3 teleSubCaptureType:(int)arg4 stillDuringVideo:(bool)arg5 frontCamera:(bool)arg6;
- (void)reportStereoFusionProcessingTypeForCaptureType:(int)arg1 isStereoFusionCapture:(bool)arg2 wideSubCaptureType:(int)arg3 teleSubCaptureType:(int)arg4 isOriginalImage:(bool)arg5;
- (void)reportStereoFusionSampleBufferProcessorProcessingStatus:(int)arg1;

@end
