/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRUserSettings : NSObject {
    bool  _televisionPairingAllowed;
    NSUserDefaults * _userDefaults;
}

@property (nonatomic, readonly) double bluetoothDeviceResumeDuration;
@property (nonatomic, readonly) double broadcastCommandWaitDuration;
@property (nonatomic, readonly) bool hasTelevisionSocketQOSLevelSet;
@property (nonatomic, readonly) long long maxTransactionMemorySize;
@property (nonatomic, readonly) double televisionDisconnectSleepDuration;
@property (nonatomic, readonly) double televisionDisconnectWaitDuration;
@property (nonatomic, readonly) double televisionNowPlayingInfoArtworkCoalesceDuration;
@property (nonatomic, readonly) double televisionNowPlayingInfoCoalesceDuration;
@property (getter=isTelevisionPairingAllowed, nonatomic) bool televisionPairingAllowed;
@property (nonatomic, readonly) double televisionSleepAssertionOnClientConnectDuration;
@property (nonatomic, readonly) long long televisionSocketQOSLevel;
@property (nonatomic, readonly) double televisionTimeoutDuration;
@property (nonatomic, readonly) double transactionWaitDurationOnNetworkSend;
@property (nonatomic, readonly) double transactionWaitDurationOnOutOfMemory;
@property (nonatomic, readonly) double transactionWaitDurationOnXpcSend;
@property (nonatomic, readonly) bool useDebugAVRouteWithoutVolumeControl;
@property (nonatomic, readonly) bool useNoDelayOptionForTelevisionSockets;
@property (nonatomic, readonly) bool usePeerToPeerTelevisionConnections;
@property (nonatomic, readonly) bool useTelevisionSystemPairing;

+ (id)currentSettings;

- (bool)_boolValueForKey:(id)arg1 usingDefaultValue:(bool)arg2;
- (double)_doubleValueForKey:(id)arg1 usingDefaultValue:(double)arg2;
- (long long)_integerValueForKey:(id)arg1 usingDefaultValue:(long long)arg2;
- (double)bluetoothDeviceResumeDuration;
- (double)broadcastCommandWaitDuration;
- (void)dealloc;
- (bool)hasTelevisionSocketQOSLevelSet;
- (id)init;
- (bool)isTelevisionPairingAllowed;
- (long long)maxTransactionMemorySize;
- (void)setTelevisionPairingAllowed:(bool)arg1;
- (double)televisionDisconnectSleepDuration;
- (double)televisionDisconnectWaitDuration;
- (double)televisionNowPlayingInfoArtworkCoalesceDuration;
- (double)televisionNowPlayingInfoCoalesceDuration;
- (double)televisionSleepAssertionOnClientConnectDuration;
- (long long)televisionSocketQOSLevel;
- (double)televisionTimeoutDuration;
- (double)transactionWaitDurationOnNetworkSend;
- (double)transactionWaitDurationOnOutOfMemory;
- (double)transactionWaitDurationOnXpcSend;
- (bool)useDebugAVRouteWithoutVolumeControl;
- (bool)useNoDelayOptionForTelevisionSockets;
- (bool)usePeerToPeerTelevisionConnections;
- (bool)useTelevisionSystemPairing;

@end
