/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SAHACommand : SADomainCommand

@property (nonatomic, copy) NSArray *actions;
@property (nonatomic, retain) SAHAFilter *filter;
@property (nonatomic, copy) NSString *serverValidity;

+ (id)command;
+ (id)commandWithDictionary:(id)arg1 context:(id)arg2;

- (id)actions;
- (id)encodedClassName;
- (id)filter;
- (id)groupIdentifier;
- (bool)requiresResponse;
- (id)serverValidity;
- (void)setActions:(id)arg1;
- (void)setFilter:(id)arg1;
- (void)setServerValidity:(id)arg1;

@end
