/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIFocusFastScrollingEntryTrimmerDelegate : NSObject <_UIScrollViewIndexEntryTrimmerDelegate>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (bool)_scrollViewIndexEntryTrimmer:(id)arg1 entryIsPlaceholder:(id)arg2;
- (id)_scrollViewIndexEntryTrimmer:(id)arg1 placeholderEntryBetweenEntryBefore:(id)arg2 entryAfter:(id)arg3;
- (bool)_scrollViewIndexEntryTrimmer:(id)arg1 startingOrEndingEntryMustBePreserved:(id)arg2;

@end
