/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIPopoverBackgroundVisualEffectView : UIVisualEffectView

- (bool)_shouldRegenerateMasksForNewMaskView:(id)arg1;
- (void)_updateEffectViewMasks;
- (void)updateMasks;

@end
