/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIClassicWindow : UIWindow {
    bool  _scaleForiPads;
}

@property (nonatomic) bool scaleForiPads;

- (double)_adjustedWindowLevelFromLevel:(double)arg1;
- (bool)_isConstrainedByScreenJail;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_sceneReferenceBounds;
- (bool)_shouldZoom;
- (void)_updateTransformLayerForClassicPresentation;
- (bool)scaleForiPads;
- (void)setScaleForiPads:(bool)arg1;

@end
