/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOCarInfo : PBCodable <NSCopying> {
    bool  _destinationSharingEnabled;
    int  _deviceConnection;
    struct { 
        int *list; 
        unsigned long long count; 
        unsigned long long size; 
    }  _engineTypes;
    struct { 
        unsigned int screenResolution : 1; 
        unsigned int deviceConnection : 1; 
        unsigned int interactionModel : 1; 
        unsigned int navAidedDrivingStatus : 1; 
        unsigned int destinationSharingEnabled : 1; 
    }  _has;
    int  _interactionModel;
    NSString * _manufacturer;
    NSString * _model;
    int  _navAidedDrivingStatus;
    struct GEOScreenResolution { 
        double _height; 
        double _width; 
        struct { 
            unsigned int height : 1; 
            unsigned int width : 1; 
        } _has; 
    }  _screenResolution;
}

@property (nonatomic) bool destinationSharingEnabled;
@property (nonatomic) int deviceConnection;
@property (nonatomic, readonly) int*engineTypes;
@property (nonatomic, readonly) unsigned long long engineTypesCount;
@property (nonatomic) bool hasDestinationSharingEnabled;
@property (nonatomic) bool hasDeviceConnection;
@property (nonatomic) bool hasInteractionModel;
@property (nonatomic, readonly) bool hasManufacturer;
@property (nonatomic, readonly) bool hasModel;
@property (nonatomic) bool hasNavAidedDrivingStatus;
@property (nonatomic) bool hasScreenResolution;
@property (nonatomic) int interactionModel;
@property (nonatomic, retain) NSString *manufacturer;
@property (nonatomic, retain) NSString *model;
@property (nonatomic) int navAidedDrivingStatus;
@property (nonatomic) struct GEOScreenResolution { double x1; double x2; struct { unsigned int x_3_1_1 : 1; unsigned int x_3_1_2 : 1; } x3; } screenResolution;

+ (id)carInfoWithTraits:(id)arg1;

- (int)StringAsDeviceConnection:(id)arg1;
- (int)StringAsEngineTypes:(id)arg1;
- (int)StringAsInteractionModel:(id)arg1;
- (int)StringAsNavAidedDrivingStatus:(id)arg1;
- (void)addEngineType:(int)arg1;
- (void)clearEngineTypes;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (bool)destinationSharingEnabled;
- (int)deviceConnection;
- (id)deviceConnectionAsString:(int)arg1;
- (id)dictionaryRepresentation;
- (int)engineTypeAtIndex:(unsigned long long)arg1;
- (int*)engineTypes;
- (id)engineTypesAsString:(int)arg1;
- (unsigned long long)engineTypesCount;
- (bool)hasDestinationSharingEnabled;
- (bool)hasDeviceConnection;
- (bool)hasInteractionModel;
- (bool)hasManufacturer;
- (bool)hasModel;
- (bool)hasNavAidedDrivingStatus;
- (bool)hasScreenResolution;
- (unsigned long long)hash;
- (id)initWithTraits:(id)arg1;
- (int)interactionModel;
- (id)interactionModelAsString:(int)arg1;
- (bool)isEqual:(id)arg1;
- (id)manufacturer;
- (void)mergeFrom:(id)arg1;
- (id)model;
- (int)navAidedDrivingStatus;
- (id)navAidedDrivingStatusAsString:(int)arg1;
- (bool)readFrom:(id)arg1;
- (struct GEOScreenResolution { double x1; double x2; struct { unsigned int x_3_1_1 : 1; unsigned int x_3_1_2 : 1; } x3; })screenResolution;
- (void)setDestinationSharingEnabled:(bool)arg1;
- (void)setDeviceConnection:(int)arg1;
- (void)setEngineTypes:(int*)arg1 count:(unsigned long long)arg2;
- (void)setHasDestinationSharingEnabled:(bool)arg1;
- (void)setHasDeviceConnection:(bool)arg1;
- (void)setHasInteractionModel:(bool)arg1;
- (void)setHasNavAidedDrivingStatus:(bool)arg1;
- (void)setHasScreenResolution:(bool)arg1;
- (void)setInteractionModel:(int)arg1;
- (void)setManufacturer:(id)arg1;
- (void)setModel:(id)arg1;
- (void)setNavAidedDrivingStatus:(int)arg1;
- (void)setScreenResolution:(struct GEOScreenResolution { double x1; double x2; struct { unsigned int x_3_1_1 : 1; unsigned int x_3_1_2 : 1; } x3; })arg1;
- (void)writeTo:(id)arg1;

@end
