/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEONSURLSharedSessionTaskDelegate : NSObject {
    <NSURLSessionDataDelegate> * _delegate;
    struct { 
        unsigned int delegateRespondsToDidFinishCollectingMetrics : 1; 
        unsigned int delegateRespondsToDataTaskDidReceiveResponse : 1; 
        unsigned int delegateRespondsToDataTaskDidReceiveData : 1; 
        unsigned int delegateRespondsToTaskDidCompleteWithError : 1; 
        unsigned int delegateRespondsToWillSendRequestForEstablishedConnection : 1; 
    }  _flags;
    NSOperationQueue * _queue;
}

@property (nonatomic, readonly) <NSURLSessionDataDelegate> *delegate;
@property (nonatomic, readonly) bool delegateRespondsToDataTaskDidReceiveData;
@property (nonatomic, readonly) bool delegateRespondsToDataTaskDidReceiveResponse;
@property (nonatomic, readonly) bool delegateRespondsToDidFinishCollectingMetrics;
@property (nonatomic, readonly) bool delegateRespondsToTaskDidCompleteWithError;
@property (nonatomic, readonly) bool delegateRespondsToWillSendRequestForEstablishedConnection;
@property (nonatomic, readonly) NSOperationQueue *queue;

+ (id)taskDelegate:(id)arg1 delegateQueue:(id)arg2;

- (void)dealloc;
- (id)debugDescription;
- (id)delegate;
- (bool)delegateRespondsToDataTaskDidReceiveData;
- (bool)delegateRespondsToDataTaskDidReceiveResponse;
- (bool)delegateRespondsToDidFinishCollectingMetrics;
- (bool)delegateRespondsToTaskDidCompleteWithError;
- (bool)delegateRespondsToWillSendRequestForEstablishedConnection;
- (id)queue;

@end
