/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOPDAssociatedApp : PBCodable <NSCopying> {
    NSMutableArray * _alternateAppAdamIds;
    NSString * _preferredAppAdamId;
}

@property (nonatomic, retain) NSMutableArray *alternateAppAdamIds;
@property (nonatomic, readonly) bool hasPreferredAppAdamId;
@property (nonatomic, retain) NSString *preferredAppAdamId;

+ (Class)alternateAppAdamIdType;
+ (id)associatedAppForPlaceData:(id)arg1;

- (void)addAlternateAppAdamId:(id)arg1;
- (id)alternateAppAdamIdAtIndex:(unsigned long long)arg1;
- (id)alternateAppAdamIds;
- (unsigned long long)alternateAppAdamIdsCount;
- (void)clearAlternateAppAdamIds;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasPreferredAppAdamId;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (id)preferredAppAdamId;
- (bool)readFrom:(id)arg1;
- (void)setAlternateAppAdamIds:(id)arg1;
- (void)setPreferredAppAdamId:(id)arg1;
- (void)writeTo:(id)arg1;

@end
