/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVContentKeyRequest : NSObject {
    AVContentKeyRequestInternal * _contentKeyRequest;
}

@property (readonly) bool canProvidePersistableContentKey;
@property (readonly) NSError *error;
@property (readonly) id identifier;
@property (nonatomic, readonly) NSData *initializationData;
@property (readonly) long long status;

- (id)_asset;
- (void)_clearContext;
- (struct OpaqueFigCPECryptor { }*)_figCryptor;
- (void)_handleKeyResponseError:(int)arg1;
- (int)_prepareForKeyRenewal;
- (void)_setError:(id)arg1;
- (void)_setStatus:(long long)arg1;
- (bool)canProvidePersistableContentKey;
- (id)contentKeyRequestDataForApp:(id)arg1 contentIdentifier:(id)arg2 options:(id)arg3 error:(id*)arg4;
- (void)dealloc;
- (id)error;
- (id)identifier;
- (id)initWithContentKeySession:(id)arg1 identifier:(id)arg2 initializationData:(id)arg3 providesPersistableKey:(bool)arg4 context:(id)arg5 asset:(id)arg6;
- (id)initializationData;
- (void)makeStreamingContentKeyRequestDataForApp:(id)arg1 contentIdentifier:(id)arg2 options:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)processContentKeyResponse:(id)arg1;
- (void)processContentKeyResponseData:(id)arg1;
- (void)processContentKeyResponseError:(id)arg1;
- (void)renewExpiringContentKeyResponseData;
- (void)respondByRequestingPersistableContentKeyRequest;
- (long long)status;

@end
