/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVContentKeyRequestInternal : NSObject {
    AVWeakReference * _assetWeakRef;
    <NSObject> * _context;
    NSError * _error;
    struct OpaqueFigCPECryptor { } * _figCryptor;
    id  _identifier;
    NSData * _initializationData;
    bool  _providesPersistableKey;
    AVContentKeySession * _session;
    long long  _status;
}

@end
